version : '2.1'

services:
  registry:
    container_name: registry
    image: registry
    restart: always
    ports:
      - 8761:8761
  serviceone:
    container_name: serviceone
    image: serviceone
    restart: always
    ports:
      - 80:80
    depends_on:
      - registry
    environment:
      - eureka.client.serviceUrl.defaultZone=http://registry:8761/eureka/
  servicetwo:
    container_name: servicetwo
    image: servicetwo
    restart: always
    ports:
      - 8082:8082
    depends_on:
      - registry
    environment:
      - eureka.client.serviceUrl.defaultZone=http://registry:8761/eureka/
  servicethree:
    container_name: servicethree
    image: servicethree
    restart: always
    ports:
      - 8083:8083
    depends_on:
      - registry
    environment:
      - eureka.client.serviceUrl.defaultZone=http://registry:8761/eureka/
  task2:
    container_name: task2
    image: task2
    restart: always
    ports:
      - 9090:9090
